### ISSUE TITLE
what does the package do in practical terms?

### ISSUE THREAD

**Issue by ville-h** [elken/yasnippet-capf#12]
What does the package do in practical terms? I am not very familiar with how emacs completion works, so just saying "capf" doesn't quite light up the bulb for me.

Let's say I use `company` to show completions and currently have `company-capf` and  `company-yasnippet` as its backends for various modes. Would the addition of this package make yasnippets work with backends set to `company-capf` only? Would this then help the completion accuracy and/or ordering?

I know this is not really an issue per se, but didn't see discussions feature enabled for this project where I could ask this kind of question.

**Comment by elken** [comment]
> What does the package do in practical terms? I am not very familiar with how emacs completion works, so just saying "capf" doesn't quite light up the bulb for me.

 The [manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion.html) has a whole section on completion which should be a good starting point.

> Let's say I use `company` to show completions and currently have `company-capf` and `company-yasnippet` as its backends for various modes. Would the addition of this package make yasnippets work with backends set to `company-capf` only? 

I don't use company so I can't comment for certain on how that interacts but in theory yes

> Would this then help the completion accuracy and/or ordering?

Shouldn't do, but as before I don't use company so I'm not familiar with how `company-yasnippet` does anything there.

> I know this is not really an issue per se, but didn't see discussions feature enabled for this project where I could ask this kind of question.

That's fine, I'juve just added them. Hope this answers everything :smile:
