### ISSUE TITLE
`(setopt corfu-on-exact-match 'show)` can be suggested in the readme

### ISSUE THREAD

**Issue by KaratasFurkan** [elken/yasnippet-capf#17]
Hi, first of all, thanks for the package. I just wanted to save some others time by suggesting this. I've spend ~30mins to find why the yasnippet candidates expands themselves when there is only one candidate. It turns out the default value of `corfu-on-exact-match` is `'insert` so when there is only one candidate and it's coming from `yasnippet-capf`, it's expanded immediately since its `:exit-function` is `yas-expand`. Setting `(setopt corfu-on-exact-match 'show)` resolved the issue.

**Comment by elken** [comment]
Thanks for reporting this, but I'd rather not add a note about Corfu that'll probably change without notice one day. If someone else runs into the same problem, they'll find this issue :smile:

**Comment by KaratasFurkan** [comment]
Makes sense, thank you :+1:

**Comment by elken** [comment]
No problem; thanks for solving it!
