### ISSUE TITLE
calling cape-yasnippet interactively on a blank line returns no completions

### ISSUE THREAD

**Issue by LemonBreezes** [elken/yasnippet-capf#18]
After db12b55cd08b614cbba134008566e48d7faf660e, this issue has reappeared. I am interested in fixing the issues you had with the previous PR if you would provide more information on which candidates broke.

**Comment by elken** [comment]
After I realized it was that commit causing it, basically everything. I'll look into it when I can but I'm happy with the behaviour for now.
