### ISSUE TITLE
Fix for not expanding snippets

### ISSUE THREAD

**Issue by thorstengrothe** [elken/yasnippet-capf#22]
This fix refers to my issue [Completions are nil](https://github.com/elken/yasnippet-capf/issues/21).

In the meantime I found the problem. It is not enough to register `yasnippet-capf` with

```
:init
(add-to-list 'completion-at-point-functions #'yasnippet-capf)
```
One must write it in a hook, like so

```
 (defun my-cape-capf-setup-latex ()
    (let ((result))
      (dolist (element '(yasnippet-capf) result)
        (add-to-list 'completion-at-point-functions element))))
```

and register it under` cape` for the equivalent modes:

```
(use-package cape
  :ensure t
  :after corfu
  :hook
  (emacs-lisp-mode . my-cape-capf-setup-latex)
  ....)
```
I guess this should be mentioned in the docs. Now it works perfectly for me :-)

**Comment by elken** [comment]
Your hook is very unnecessary code-wise, you just need the `add-to-list` call. Sounds like you might have something else that updates the list of functions, but sure I'll add a doc note about maybe needing a hook.
